#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m space 1 --label misc 
yabai -m space 2 --label terminal
yabai -m space 3 --label slack
yabai -m space 4 --label browser-work
yabai -m space 5 --label browser-private
yabai -m space 6 --label six
yabai -m space 9 --label nine

yabai -m rule --add app=Alacritty space=terminal
yabai -m rule --add app=Slack space=slack
yabai -m rule --add app=Brave space=browser-private
yabai -m rule --add app=Brave title="Work$" space=browser-work

# bar settings
# yabai -m config status_bar                   off
# # yabai -m config status_bar_text_font         "Helvetica Neue:Bold:12.0"
# # yabai -m config status_bar_icon_font         "FontAwesome:Regular:12.0"
# # yabai -m config status_bar_background_color  0xff202020
# # yabai -m config status_bar_foreground_color  0xffa8a8a8
# # yabai -m config status_bar_space_icon_strip  I II III IV V VI VII VIII IX X
# # yabai -m config status_bar_power_icon_strip  ? ?
# # yabai -m config status_bar_space_icon        ?
# # yabai -m config status_bar_clock_icon        ?

# # global settings
## WITH SIP ENABLED (Installed Limelight seperately, Don't need this)
# yabai -m config window_border off

## WTIH SIP DISABLED (Limelight build into Yabai, enable it here)
yabai -m config window_border on
yabai -m config window_border_width 3
yabai -m config active_window_border_color 0xFF40FF00
yabai -m config normal_window_border_color 0x00FFFFFF
yabai -m config insert_feedback_color        0xffd75f5f

yabai -m config window_opacity               off
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        1.0

yabai -m config mouse_modifier               ctrl
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  2
yabai -m config bottom_padding               2
yabai -m config left_padding                 2
yabai -m config right_padding                2
yabai -m config window_gap                   2

# float system preferences. Most of these just diable Yabai form resizing them.
yabai -m rule --add app="^System Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Karabiner-Elements$" sticky=on layer=above manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" sticky=on layer=above manage=off
yabai -m rule --add app="^Finder$" sticky=on layer=above manage=off
yabai -m rule --add app="^Disk Utility$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Information$" sticky=on layer=above manage=off
yabai -m rule --add app="^Activity Monitor$" sticky=on layer=above manage=off
yabai -m rule --add app="^Music$" manage=off
yabai -m rule --add app="^ForkLift$" manage=off
yabai -m rule --add app="^TV$" manage=off

echo "yabai configuration loaded.."
